using System.Reflection;
using System.Text.Json;

namespace Precomp4C {
    static class Program {
        static readonly Assembly Asm = Assembly.GetExecutingAssembly();
        static readonly string FullNameWithVersion = Asm.GetCustomAttribute<AssemblyProductAttribute>().Product + " V" + Asm.GetName().Version.ToString();
        static readonly string FormalName = Asm.GetCustomAttribute<AssemblyCompanyAttribute>().Company + " - " + FullNameWithVersion;
        static readonly string RepoURL = Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyMetadataAttribute>().Value;
        static readonly string ConfigFile = Asm.GetName().Name + ".config.json";
        static string ProjectDir;
        static CConfigObject ConfigObject;
        static void ShowHelp() {
            Console.WriteLine(FormalName);
            Console.WriteLine();
            Console.WriteLine("Syntax: " + Asm.GetName().Name + " ProjectDir");
            Console.WriteLine("  ProjectDir: Path to the project directory, equals to Visual Studio macro $(ProjectDir), which should contains " + Asm.GetName().Name + " config file (" + ConfigFile + ")");
            Console.WriteLine();
            Console.WriteLine("For more information, see " + RepoURL);
            Console.WriteLine();
        }
        public static void WriteOutputHeadInfo(FileStream Output) {
            Output.Write(new byte[] { 0xEF, 0xBB, 0xBF });
            RTL.WriteOutput(Output, "//------------------------------------------------------------------------------");
            RTL.WriteOutput(Output, "// <auto-generated>");
            RTL.WriteOutput(Output, "//     This code was generated by " + Asm.GetName().Name);
            RTL.WriteOutput(Output, "//     " + FormalName);
            RTL.WriteOutput(Output, "//     " + RepoURL);
            RTL.WriteOutput(Output, "//     Do not change this file manually");
            RTL.WriteOutput(Output, "// </auto-generated>");
            RTL.WriteOutput(Output, "//------------------------------------------------------------------------------\r\n");
        }
        static int Main(string[] args) {

            // Resolve command line arguments
            if (args.Length != 1 || args[0] == "/?" || args[0].ToUpper() == "/HELP") {
                ShowHelp();
                Environment.Exit(0);
            }
            ProjectDir = args[0];
            if (!Directory.Exists(ProjectDir)) {
                RTL.RaiseError(1, "Specified ProjectDir (" + ProjectDir + ") not exists");
            }
            if (ProjectDir[^1] != '\\') {
                ProjectDir += '\\';
            }

            // Read config file
            string ConfigText = string.Empty, ConfigFilePath = ProjectDir + ConfigFile;
            try {
                ConfigText = File.ReadAllText(ConfigFilePath);
            } catch {
                RTL.RaiseError(2, "Read config file (" + ConfigFilePath + ") failed");
            }
            string OutputName = string.Empty, OutputHeaderPath = string.Empty, OutputSourcePath = string.Empty;
            try {
                ConfigObject = JsonSerializer.Deserialize<CConfigObject>(ConfigText);
                OutputName = Path.GetFullPath(ProjectDir + (ConfigObject.Output ?? Asm.GetName().Name + ".Output"));
                OutputHeaderPath = OutputName + ".h";
                OutputSourcePath = OutputName + ".c";
            } catch {
                RTL.RaiseError(3, "Invalid configurations");
            }

            // Check last modify date
            DateTime LoaderModifyTime, LastModifyTime = File.GetLastWriteTime(ConfigFilePath);
            if (ConfigObject.Loaders.I18N != null) {
                LoaderModifyTime = Loaders.I18N.GetLastModifyTime(ProjectDir, ConfigObject.Loaders.I18N);
                if (LoaderModifyTime > LastModifyTime) {
                    LastModifyTime = LoaderModifyTime;
                }
            }
            if (ConfigObject.Loaders.SymExtract != null) {
                LoaderModifyTime = Loaders.SymExtract.GetLastModifyTime(ProjectDir, ConfigObject.Loaders.SymExtract);
                if (LoaderModifyTime > LastModifyTime) {
                    LastModifyTime = LoaderModifyTime;
                }
            }
            if (ConfigObject.Loaders.Binary != null) {
                LoaderModifyTime = Loaders.Binary.GetLastModifyTime(ProjectDir, ConfigObject.Loaders.Binary);
                if (LoaderModifyTime > LastModifyTime) {
                    LastModifyTime = LoaderModifyTime;
                }
            }

            // Compile
            if (LastModifyTime > File.GetLastWriteTime(OutputHeaderPath) ||
                LastModifyTime > File.GetLastWriteTime(OutputSourcePath)) {
                FileStream fsHeader = null, fsSource = null;
                try {
                    fsHeader = File.Create(OutputHeaderPath);
                    fsSource = File.Create(OutputSourcePath);
                } catch {
                    RTL.RaiseError(4, "Write output files (" + OutputName + ".(h/c)) failed");
                }
                WriteOutputHeadInfo(fsHeader);
                WriteOutputHeadInfo(fsSource);
                RTL.WriteOutput(fsHeader, "#pragma once\r\n");
                if (ConfigObject.NTAssassinIntegrate != null && !string.IsNullOrEmpty(ConfigObject.NTAssassinIntegrate)) {
                    string IncludeHeader = "#include \"" + ConfigObject.NTAssassinIntegrate + "\"\r\n";
                    RTL.WriteOutput(fsHeader, IncludeHeader);
                    RTL.WriteOutput(fsSource, IncludeHeader);
                }
                // Loaders process
                if (ConfigObject.Loaders.I18N != null) {
                    Loaders.I18N.Process(ProjectDir, fsHeader, fsSource, ConfigObject.Loaders.I18N);
                }
                if (ConfigObject.Loaders.SymExtract != null) {
                    Loaders.SymExtract.Process(ProjectDir, fsHeader, fsSource, ConfigObject.Loaders.SymExtract);
                }
                if (ConfigObject.Loaders.Binary != null) {
                    Loaders.Binary.Process(ProjectDir, fsHeader, fsSource, ConfigObject.Loaders.Binary);
                }
                // Cleanup
                fsHeader.Dispose();
                fsSource.Dispose();

                Console.WriteLine("Precomp4C writes (" + OutputName + ".(h/c)) successfully");
            } else {
                Console.WriteLine("Precomp4C outputs (" + OutputName + ".(h/c)) is up-to-date");
            }

            return 0;
        }
    }
}
